projects:
  - name: Linee guida su acquisizione e riuso di software per le Pubbliche Amministrazioni
    short_name: Linee guida riuso software
    description: |
      Le linee guida su acquisizione e riuso di software per le pubbliche
      amministrazioni sono adottate in attuazione dagli articoli 68 e 69 del
      Codice dell’Amministrazione Digitale; il documento e la metodologia in
      esso descritta sono da intendersi come ausilio a un percorso decisionale
      che rimane sotto la piena responsabilità delle amministrazioni.
      Attualmente, queste linee guida, sono soggette a notifica alla Commissione
      Europea, in esecuzione della direttiva 2015/1535.
    website: https://www.agid.gov.it/
    logo: assets/images/logo-agid.png
    documents:
      - lg-acquisizione-e-riuso-software-per-pa-docs
  - name: Competenze digitali
    short_name: Competenze digitali
    description: |
      L’Agenzia per l’Italia Digitale si occupa di supportare la definizione
      delle competenze digitali per le professionalità operanti nel settore
      dell’Information and Communication Technology (ICT) e per i soggetti che
      utilizzano l’ICT all’interno delle attività lavorative, sia per ruoli di
      tipo operativo che manageriale. Le attività di AGID sono finalizzate alla
      catalogazione e allo sviluppo  di competenze digitali di base, di
      e-leadership e specialistiche, con particolare attenzione alle nuove
      professioni e al mondo delle piccole imprese per fornire linee guida di
      riferimento per supportare la crescita digitale.
    website: https://www.agid.gov.it/
    logo: assets/images/logo-agid.png
    documents:
      - lg-competenze-digitali-base-docs
      - lg-competenze-digitali-specialistiche-armonizzazione-docs
      - lg-competenze-digitali-specialistiche-qualita-docs
      - lg-competenze-digitali-eleadership-docs
